version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd packaging-and-delivery-service
      - mvn clean package
      - echo Building the docker image
      - docker build -t packaging-and-delivery-service .
      - docker tag packaging-and-delivery-service 156962844638.dkr.ecr.ap-southeast-1.amazonaws.com/yuva-packaging-and-delivery-service-repo-ecr:PackagingAndDeliveryService
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(docker images)
      - docker push 156962844638.dkr.ecr.ap-southeast-1.amazonaws.com/yuva-packaging-and-delivery-service-repo-ecr:PackagingAndDeliveryService
      - echo Writing definition files
      - printf '[{"name":"PackagingAndDeliveryService-container","imageUri":"%s"}]' 156962844638.dkr.ecr.ap-southeast-1.amazonaws.com/yuva-packaging-and-delivery-service-repo-ecr:PackagingAndDeliveryService > taskdefinition.json

artifacts:
  files: packaging-and-delivery-service/taskdefinition.json


